ssh: Fix public key only configuration
Use the correct igconf option to inspect the variable governing whether
public key only auth should be used.

Ensure igconf reports an error and exits non-zero if an unsupported
option is provided. Unfortunately, this won't trigger a build failure
because scripts in the YAML are executed in a new process, and
enforcing strict shell behaviour for the whole build is not viable.

diff --git a/bin/igconf b/bin/igconf
--- a/bin/igconf
+++ b/bin/igconf
@@ -103,6 +103,7 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]] ; then
          exit $?
          ;;
       *)
+         >&2 echo "Error: invalid igconf op ($op) args: $@" ; exit 1
          ;;
    esac
    exit 1
