Improve PATH support
Extend PATH support to external directories IGconf_ext_dir and
IGconf_ext_nsdir. If they have a bin sub-directory it will be included
in PATH at rootfs creation and image generation stages. This enables
all bdebstrap hooks (including those in image and board directories)
and all post-build stages to be able to locate and use executables in
these directories if they wish.

Invoke bdebstrap from the rpi-image-gen top level directory. Special
mmdebstrap hooks like copy-in, upload, etc (which are available in
bdebstrap YAML) default their path outside the chroot to the
the current directory of the original mmdebstrap invocation. While it
was previously possible to invoke build.sh from anywhere, this meant
that the path outside the chroot for these special hooks was not
deterministic which limited their usability somewhat. By always invoking
bdebstrap within the top level directory, these special hooks now have a
defined reference point for their path outside the chroot meaning they
can be used reliably and regardless of where build.sh is invoked from.

Add a new directory which is intended to hold common, native arch
rpi-image-gen programs and executable scripts, relocating the hook
wrapper to there. This directory is also included in PATH for rootfs
and image stages.

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -35,6 +35,22 @@ run()
 export -f run
 
 
+rund()
+{
+   if [ "$#" -gt 1 ] && [ -d  "$1" ] ; then
+      local _dir="$1"
+      shift 1
+      env -C "$_dir" "$@"
+      _ret=$?
+      if [[ $_ret -ne 0 ]]
+      then
+         die "Error: ["$@"] ($_ret)"
+      fi
+   fi
+}
+export -f rund
+
+
 bootstrap(){
 	local BOOTSTRAP_CMD=debootstrap
 	local BOOTSTRAP_ARGS=()
