New top level tree
Migrate examples/mm64/bootstrap/ to top level.
Move legacy pi-gen directories to legacy/

Lots of TODOs, including shellchecking.

Additional customisation and features are planned.

All image-gen variables are assigned a common name prefix. Config and
option variables are aggregated and provided in the environment to both
rootfs creation (bdebstrap) and genimage image pre/post generation
(hooks) stages. Variables added to a config file or options file are
automatically included.

Assembly of the YAML paths for bdebstrap now incorporate additional
directories when searching for a layer within a profile. This allows
external YAML files to be incorporated and aggregated by bdebstrap to
provide a defined mechanism for rootfs customisation. This is best
demonstrated by examples/custom_layers/

Add new meta layers for 2712 kernel and multi-arch derrivative of
bookworm+apt (ie. native arm64 with armhf userland).

Add image layout mbr/simple_dual which has two partitions - one vfat and
one ext4.

Add various helpers to scripts/common. Logging to file not currently
used.

Add automatic dependency installer.

Remove legacy examples and add some new ones.

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -1,7 +1,39 @@
+msg() {
+   date +"[%T] $*"
+}
+export -f msg
+
+
 log (){
-	date +"[%T] $*" | tee -a "${LOG_FILE}"
+  msg "$*" | tee -a "${LOG_FILE}"
 }
 export -f log
+
+
+err (){
+   >&2 msg "$*"
+}
+export -f err
+
+
+die (){
+   err "$*"
+   exit 1
+}
+export -f die
+
+
+run()
+{
+   env "$@"
+   _ret=$?
+   if [[ $_ret -ne 0 ]]
+   then
+      die "Error: ["$@"] ($_ret)"
+   fi
+}
+export -f run
+
 
 bootstrap(){
 	local BOOTSTRAP_CMD=debootstrap
@@ -158,21 +190,49 @@ ensure_loopdev_partitions() {
 }
 export -f ensure_loopdev_partitions
 
+
+# .ini file section parser reading key value pairs into the env as shell variables.
+# key names will be prefixed with section name and converted to lower case, e.g.
+#
+# [mysection]
+# foo=zzz
+# BAR=yyy
+#
+# will yield:
+# IGconf_mysection_foo=zzz
+# IGconf_mysection_bar=yyy
+#
 read_config_section() {
    local section=$1
    local cfg=$2
    local attrs=$(crudini --get --format=sh $cfg $section)
    if [ $? -eq 0 ] ; then
       while IFS="=" read -r key value ; do
-         eval IGconf_"${section}"_"${key}"="$value"
+         [[ "$key" =~ ^#.*$ ]] && continue
+         [[ "$key" =~ ^$ ]] && continue
+         if [[ ! -n "$value" ]] ; then
+            eval unset IGconf_"${section,,}"_"${key,,}"
+         else
+            eval IGconf_"${section,,}"_"${key,,}"="$value"
+         fi
       done < <(printf '%s\n' "$attrs")
    fi
 }
 export -f read_config_section
 
 
+# shell variable list parser reading key value pairs into the env. key names
+# will be prefixed and converted to lower case, e.g.
+#
+# foo=zzz
+# BAR=yyy
+#
+# will yield:
+# IGconf_foo=zzz
+# IGconf_bar=yyy
+#
 read_options() {
-   if [ -s "$1" ] ; then
+   if [[ $# -eq 1 && -f $1 ]] ; then
       local attrs=$(cat $1)
    else
       local attrs=$(cat)
@@ -180,8 +240,11 @@ read_options() {
    while IFS="=" read -r key value ; do
       [[ "$key" =~ ^#.*$ ]] && continue
       [[ "$key" =~ ^$ ]] && continue
-      [[ "$value" =~ ^$ ]] && continue
-      eval IGopt_"${key}"="$value"
+      if [[ "$value" =~ ^$ ]] ; then
+         eval unset IGconf_"${key,,}"
+      else
+         eval IGconf_"${key,,}"="$value"
+      fi
    done < <(printf '%s\n' "$attrs")
 }
 export -f read_options
diff --git a/scripts/dependencies_check b/scripts/dependencies_check
--- a/scripts/dependencies_check
+++ b/scripts/dependencies_check
@@ -6,26 +6,37 @@
 # named for the tool (i.e., qemu-user-static).
 dependencies_check()
 {
-	local depfile deps missing
+	local depfile deps missing=() op=$1
+
+	if [[ "$op" == install ]] ; then
+		shift 1
+	fi
 
 	for depfile in "$@"; do
 		if [[ -e "$depfile" ]]; then
-			deps="$(sed -f "${SCRIPT_DIR}/remove-comments.sed" < "${BASE_DIR}/depends")"
+			deps="$(sed -f "${IGTOP}/scripts/remove-comments.sed" < "${IGTOP}/depends")"
 
 		fi
 		for dep in $deps; do
 			if ! hash "${dep%:*}" 2>/dev/null; then
-				missing="${missing:+$missing }${dep#*:}"
+				missing+=("${dep#*:}")
 			fi
 		done
 	done
 
-	if [[ "$missing" ]]; then
+	if [[ "${missing[@]}" ]]; then
 		echo "Required dependencies not installed"
 		echo
 		echo "This can be resolved on Debian/Raspbian systems by installing:"
-		echo "$missing"
+		echo "${missing[@]}"
+		echo
+		echo "Script install_deps.sh can be used for this purpose."
+		echo
 		false
+
+		if [[ "$op" == install ]] ; then
+			apt install -y "${missing[@]}"
+		fi
 	fi
 
     # If we're building on a native arm platform, we don't need to check for
@@ -50,4 +61,13 @@ dependencies_check()
 			exit 1
 		fi
 	fi
+}
+
+
+dependencies_install()
+{
+	if [ "$(id -u)" != "0" ]; then
+		>&2 echo "Please run as root to install dependencies."; exit 1
+	fi
+	dependencies_check install "$@"
 }
