Extend bdebstrap hooks to image and board
An image or board may need to utilise bdebstrap hooks rather than being
limited to a post-build hook. The bdebstrap hooks execute in the context
of bdebstrap invocation, which mean they operate on the chroot as it is
being created and at the respective stage (i.e. setup, essential,
customize and cleanup). Adding support of these hooks to image and board
broadens the scope of what can be performed outside of the meta layers
and enables further customisation options.

One example of why these hooks may be useful would be if an image layout
wanted to install files in the initramfs that were required for specific
reasons. It would be simpler to install the files in the rootfs using a
customize hook during chroot creation rather than afterwards at
post-build.

diff --git a/scripts/runner b/scripts/runner
--- a/scripts/runner
+++ b/scripts/runner
@@ -2,22 +2,25 @@
 
 set -u
 
-case "$1" in
+op="$1"
+shift 1
+
+case "$op" in
    setup|extract|essential|customize|cleanup)
-      # Execute scripts in $2 that start with “setup”, “extract”, etc
-      dir=$(realpath -m "$2")
-      [[ -d "$dir" ]] || {>&2 echo runner: invalid dir $dir ; exit 1;}
-      scripts=("${dir}/${1}"*)
-      shift 2
-      for s in "${scripts[@]}" ; do
-         if [ -x "$s" ] ; then
-            bash "$s" "$@"
-            err=$?
-            if [ $err -ne 0 ] ; then
-               >&2 echo "runner: $s error ($err)"
-               exit $err
+      # Execute scripts from within these dirs that start with “setup”, “extract”, etc
+      for dir in ${IGTOP}/scripts/bdebstrap ${IGIMAGE}/bdebstrap ${IGBOARD}/bdebstrap ; do
+         [[ -d "$dir" ]] || continue
+         scripts=("${dir}/${op}"*)
+         for script in "${scripts[@]}" ; do
+            if [ -x "$script" ] ; then
+               env -C "$dir" bash "$(basename "$script")" "$@"
+               err=$?
+               if [ $err -ne 0 ] ; then
+                  >&2 echo "runner: $script error ($err)"
+                  exit $err
+               fi
             fi
-         fi
+         done
       done
       ;;
    *)
